[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"

[deploy]
startCommand = "sh start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
