services:
  - type: web
    name: nlp-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --workers 1 --threads 4 --bind 0.0.0.0:$PORT websocket_api:app
    envVars:
      - key: WHISPER_MODEL
        value: tiny
      - key: CHUNK_SECONDS
        value: "5"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"
